[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"

[profile.release]
opt-level = 2

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals", "--enable-reference-types"]
